version: '3'
services:
  zipkin:
    image: openzipkin/zipkin
    environment:
      - RABBIT_ADDRESSES=http://192.168.42.11:15672
      - RABBIT_USER=guest
      - RABBIT_PASSWORD=guest

    ports:
      - "9411:9411"