version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.7.6-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - "TZ=@timezone@"
    networks:
      - local

  zipkin:
    image: openzipkin/zipkin:2.10.2
    container_name: zipkin
    depends_on:
      - rabbitmq
    ports:
      - "9411:9411"
    environment:
      - "TZ=@timezone@"
      - "RABBIT_URI=amqp://guest:guest@rabbitmq:5672"
    networks:
      - local

  netflix-eureka-naming-server:
    image: tomek371240/netflix-eureka-naming-server:1
    depends_on:
      - zipkin
    networks:
      - local
    ports:
      - "8761:8761"

  currency-exchange-service2:
    image: tomek371240/currency-exchange-service:2.1
    depends_on:
      - netflix-eureka-naming-server
    networks:
      - local
    ports:
      - "8000:8000"

networks:
  local: