version: '2'
services:
  zipkin:
  container_name: zipkin
  image: openzipkin/zipkin
  environment:
    - RABBIT_ADDRESSES=http://192.168.42.11:15672:5672
    - RABBIT_USER=guest
    - RABBIT_PASSWORD=guest
  ports:
    - 9411:9411